spring:
  application:
    name: caching
  logging:
    level:
      org:
        springframework:
          web: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
